---

- name: install rabbitmq-server
  yum: name=rabbitmq-server state=present

- name: enable rabbitmq_management plugin
  rabbitmq_plugin: names=rabbitmq_management state=enabled

- name: start and enable rabbitmq-server
  service: name=rabbitmq-server state=started enabled=yes

- name: add rabbitmq user
  rabbitmq_user: user={{ item.user }} password={{ item.password }} vhost={{ item.vhost }}
                 configure_priv={{ item.configure_priv }} read_priv={{ item.read_priv }}
                 write_priv={{ item.write_priv }} tags={{ item.tags }} state={{ item.state }}
  with_items: "{{ rabbitmq_user | default([]) }}"
  when: rabbitmq_user is defined

- name: delete guest user
  rabbitmq_user: user=guest state=absent
  when: delete_guest_user

